/**
 * SendEmail class performs sending email over SMTP connection
 * 
 * @author Team ATS
 * @version 1.0
 */
package helpers;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class SendEmail {

	/**
	 * This constructor is used for sending email
	 * 
	 * @param summaryResult String - summary as a email content
	 * @param toAddress String
	 * @param content String - other email content by user
	 * @param subject	 * 
	 * @return boolean - this will return true if mail is successfully sent else will return false
	 */
	public boolean sendEmail(String summaryResult, String toAddress,
			String content, String subject) {
		// System.out.println("Calling constructor");
		final String username = "youremail@example.com";
		final String password = "yourpassword";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
				new javax.mail.Authenticator() {
					protected PasswordAuthentication getPasswordAuthentication() {
						return new PasswordAuthentication(username, password);
					}
				});

		try {

			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(
					"MissionImpossible044@gmail.com"));
			message.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(toAddress));
			message.setSubject(subject);
			String mailContent = content + "\n\n";
			mailContent += summaryResult + "\n\n";
			mailContent += "Disclaimer :\n This email is generated by AutoTextSummarizer System";
			message.setText(mailContent);

			Transport.send(message);
			return true;

		} catch (MessagingException e) {
			e.printStackTrace();
		}
		return false;

	}
}
